package net.ow.shared.commonlog.provider.trace;

import io.micrometer.common.lang.NonNullApi;
import jakarta.servlet.http.HttpServletRequest;
import lombok.NoArgsConstructor;
import net.ow.shared.commonlog.utils.TraceIdUtils;

@NonNullApi
@NoArgsConstructor
public class DefaultTraceIdProvider implements TraceIdProvider {
    /**
     * Generates a trace ID for the request.
     *
     * <p>This method generates and returns a trace ID used to track the request's flow through the
     * system. The trace ID is generated by calling the TraceIdUtils.generateTraceId() method.
     *
     * @param request HTTP request object, this parameter is currently unused but may be used for
     *     future extensions
     * @return Generated trace ID, guaranteed to be non-null
     */
    @Override
    public String getTraceId(HttpServletRequest request) {
        return TraceIdUtils.generateTraceId();
    }
}
