name: Remove SNAPSHOT suffix

on:
  pull_request:
    branches:
      - main

jobs:
  remove-snapshot-suffix:
    if: "${{ startsWith(github.event.pull_request.title, '[RELEASE]') && startsWith(github.ref_name, 'release-'}}"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Remove SNAPSHOT suffix
        uses: lllIIIIlll/actions/maven-remove-snapshot-suffix@main
        with:
          nexus-user: ${{ secrets.NEXUS_USERNAME }}
          nexus-password: ${{ secrets.NEXUS_PASSWORD }}
          includes-dependencies: net.ow.shared:*